spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_manager
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.format_sql: true
logging:
  level:
    org:
      springframework:
        security: debug
      hibernate:
        type: trace

api:
  security:
    token: ${JWT_SECRET:my-secret}

web:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST
    max-age: 3600