name: CI - Test and build

on: [push, pull_request]

jobs:
  unit-tests:
    name: Backend tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: JDK 17 setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and Test
        run: |
          cd api
          mvn clean test